# Site settings
title: "Digital Repository of Cheuk Kit (Philip) Chung"
description: "A digital repository exhibiting the archival materials of Cheuk Kit (Philip) Chung"
author: "Cheuk Kit (Philip) Chung"
email: ookkchung8@gmail.com
baseurl: "/digital-repository"
url: "https://wongsyvr.github.io"

# GitHub Pages settings
repository: wongsyvr/digital-repository

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collection Settings
collections:
  items:
    output: true
    permalink: /:collection/:name
    source: _items

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "items"
    values:
      layout: item

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
